// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Config = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_IPMinus = NULL;
lv_obj_t * ui_MinusLabel = NULL;
lv_obj_t * ui_IPDigitsBox = NULL;
lv_obj_t * ui_IPPlus = NULL;
lv_obj_t * ui_PlusLabel = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_BackButton = NULL;
lv_obj_t * ui_BackLabel = NULL;
lv_obj_t * ui_ResetButton = NULL;
lv_obj_t * ui_ResetLabel = NULL;
lv_obj_t * ui_Label6 = NULL;
// event funtions
void ui_event_IPMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_IPDigitsBox, -1);
    }
}

void ui_event_IPPlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_IPDigitsBox, 1);
    }
}

void ui_event_BackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Monitor, LV_SCR_LOAD_ANIM_OUT_TOP, 300, 0, &ui_Monitor_screen_init);
    }
}

void ui_event_ResetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        restartESP(e);
    }
}

// build funtions

void ui_Config_screen_init(void)
{
    ui_Config = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Config, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Config, lv_color_hex(0x36495A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Config, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Config);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 240);
    lv_obj_set_height(ui_Container2, 50);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, -15);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -9);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "192.168.72. ");

    ui_IPMinus = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_IPMinus, 40);
    lv_obj_set_height(ui_IPMinus, 40);
    lv_obj_set_align(ui_IPMinus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IPMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_IPMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_IPMinus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IPMinus, lv_color_hex(0x718CA2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IPMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinusLabel = lv_label_create(ui_IPMinus);
    lv_obj_set_width(ui_MinusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MinusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinusLabel, "-");
    lv_obj_set_style_text_font(ui_MinusLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPDigitsBox = lv_spinbox_create(ui_Container2);
    lv_obj_set_width(ui_IPDigitsBox, 50);
    lv_obj_set_height(ui_IPDigitsBox, 40);
    lv_obj_set_x(ui_IPDigitsBox, 73);
    lv_obj_set_y(ui_IPDigitsBox, -1);
    lv_obj_set_align(ui_IPDigitsBox, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_IPDigitsBox, 3, 0);
    lv_spinbox_set_range(ui_IPDigitsBox, 0, 255);
    lv_spinbox_set_cursor_pos(ui_IPDigitsBox, 1 - 1);
    lv_spinbox_set_value(ui_IPDigitsBox, 2);
    lv_obj_set_style_radius(ui_IPDigitsBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_IPDigitsBox, lv_color_hex(0x11425B), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IPDigitsBox, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_IPPlus = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_IPPlus, 40);
    lv_obj_set_height(ui_IPPlus, 40);
    lv_obj_set_align(ui_IPPlus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IPPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_IPPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_IPPlus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IPPlus, lv_color_hex(0x718CA2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IPPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlusLabel = lv_label_create(ui_IPPlus);
    lv_obj_set_width(ui_PlusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PlusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PlusLabel, "+");
    lv_obj_set_style_text_font(ui_PlusLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Config);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 182);
    lv_obj_set_height(ui_Container4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Container4, 0);
    lv_obj_set_y(ui_Container4, 50);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackButton = lv_button_create(ui_Container4);
    lv_obj_set_height(ui_BackButton, 40);
    lv_obj_set_width(ui_BackButton, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_BackButton, 0);
    lv_obj_set_y(ui_BackButton, -70);
    lv_obj_set_align(ui_BackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackButton, lv_color_hex(0x718CA2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackLabel = lv_label_create(ui_BackButton);
    lv_obj_set_width(ui_BackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackLabel, "Back");

    ui_ResetButton = lv_button_create(ui_Container4);
    lv_obj_set_height(ui_ResetButton, 40);
    lv_obj_set_width(ui_ResetButton, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_ResetButton, 43);
    lv_obj_set_y(ui_ResetButton, -19);
    lv_obj_set_align(ui_ResetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ResetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ResetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResetButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResetButton, lv_color_hex(0x718CA2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetLabel = lv_label_create(ui_ResetButton);
    lv_obj_set_width(ui_ResetLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResetLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResetLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResetLabel, "Restart");

    ui_Label6 = lv_label_create(ui_Config);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -70);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Config");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_IPMinus, ui_event_IPMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IPPlus, ui_event_IPPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackButton, ui_event_BackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResetButton, ui_event_ResetButton, LV_EVENT_ALL, NULL);

}

void ui_Config_screen_destroy(void)
{
    if(ui_Config) lv_obj_del(ui_Config);

    // NULL screen variables
    ui_Config = NULL;
    ui_Container2 = NULL;
    ui_Label2 = NULL;
    ui_IPMinus = NULL;
    ui_MinusLabel = NULL;
    ui_IPDigitsBox = NULL;
    ui_IPPlus = NULL;
    ui_PlusLabel = NULL;
    ui_Container4 = NULL;
    ui_BackButton = NULL;
    ui_BackLabel = NULL;
    ui_ResetButton = NULL;
    ui_ResetLabel = NULL;
    ui_Label6 = NULL;

}
