// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_CONFIG_H
#define UI_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Config
extern void ui_Config_screen_init(void);
extern void ui_Config_screen_destroy(void);
extern lv_obj_t * ui_Config;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_IPAddress;
extern void ui_event_IPMinus(lv_event_t * e);
extern lv_obj_t * ui_IPMinus;
extern lv_obj_t * ui_MinusLabel;
extern lv_obj_t * ui_IPDigitsBox;
extern void ui_event_IPPlus(lv_event_t * e);
extern lv_obj_t * ui_IPPlus;
extern lv_obj_t * ui_PlusLabel;
extern lv_obj_t * ui_Container4;
extern void ui_event_BackButton(lv_event_t * e);
extern lv_obj_t * ui_BackButton;
extern lv_obj_t * ui_BackLabel;
extern void ui_event_ResetButton(lv_event_t * e);
extern lv_obj_t * ui_ResetButton;
extern lv_obj_t * ui_ResetLabel;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_BatteryLifeLabel;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_USBSerialSwitch;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

