// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void restartESP(lv_event_t * e)
{
	// Your code here
}
