// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_LOADING_H
#define UI_LOADING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Loading
extern void ui_Loading_screen_init(void);
extern void ui_Loading_screen_destroy(void);
extern void ui_event_Loading(lv_event_t * e);
extern lv_obj_t * ui_Loading;
extern lv_obj_t * ui_Spinner1;
extern void ui_event_Expanding_Green(lv_event_t * e);
extern lv_obj_t * ui_Expanding_Green;
extern void ui_event_Expanding_Black(lv_event_t * e);
extern lv_obj_t * ui_Expanding_Black;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

