// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Monitor = NULL;
lv_obj_t * ui_LevelArc1 = NULL;
lv_obj_t * ui_LevelArc2 = NULL;
lv_obj_t * ui_LevelArc3 = NULL;
lv_obj_t * ui_MonitorArcL1 = NULL;
lv_obj_t * ui_MonitorArcR1 = NULL;
lv_obj_t * ui_MonitorArcL2 = NULL;
lv_obj_t * ui_MonitorArcR2 = NULL;
lv_obj_t * ui_MonitorArcL3 = NULL;
lv_obj_t * ui_MonitorArcR3 = NULL;
lv_obj_t * ui_LabelArcLevel = NULL;
// event funtions
void ui_event_LabelArcLevel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Config, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_Config_screen_init);
    }
}

// build funtions

void ui_Monitor_screen_init(void)
{
    ui_Monitor = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Monitor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LevelArc1 = lv_arc_create(ui_Monitor);
    lv_obj_set_width(ui_LevelArc1, 240);
    lv_obj_set_height(ui_LevelArc1, 240);
    lv_obj_set_align(ui_LevelArc1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_LevelArc1, 0, 6000);
    lv_arc_set_value(ui_LevelArc1, 2500);
    lv_obj_set_style_arc_width(ui_LevelArc1, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_LevelArc1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_LevelArc1, lv_color_hex(0x70C399), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_LevelArc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_LevelArc1, 18, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_LevelArc1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LevelArc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LevelArc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LevelArc2 = lv_arc_create(ui_Monitor);
    lv_obj_set_width(ui_LevelArc2, 200);
    lv_obj_set_height(ui_LevelArc2, 200);
    lv_obj_set_align(ui_LevelArc2, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_LevelArc2, 0, 6000);
    lv_arc_set_value(ui_LevelArc2, 2500);
    lv_obj_set_style_arc_width(ui_LevelArc2, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_LevelArc2, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_LevelArc2, lv_color_hex(0x44765C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_LevelArc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_LevelArc2, 18, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_LevelArc2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LevelArc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LevelArc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LevelArc3 = lv_arc_create(ui_Monitor);
    lv_obj_set_width(ui_LevelArc3, 160);
    lv_obj_set_height(ui_LevelArc3, 160);
    lv_obj_set_align(ui_LevelArc3, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_LevelArc3, 0, 6000);
    lv_arc_set_value(ui_LevelArc3, 2500);
    lv_obj_set_style_arc_width(ui_LevelArc3, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_LevelArc3, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_LevelArc3, lv_color_hex(0x44765C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_LevelArc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_LevelArc3, 18, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_LevelArc3, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LevelArc3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LevelArc3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MonitorArcL1 = lv_arc_create(ui_Monitor);
    lv_obj_set_width(ui_MonitorArcL1, 240);
    lv_obj_set_height(ui_MonitorArcL1, 240);
    lv_obj_set_align(ui_MonitorArcL1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MonitorArcL1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_MonitorArcL1, 0, 6000);
    lv_arc_set_value(ui_MonitorArcL1, 1400);
    lv_obj_set_style_arc_width(ui_MonitorArcL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MonitorArcL1, lv_color_hex(0x92FFC8), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MonitorArcL1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MonitorArcL1, 9, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_MonitorArcL1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MonitorArcL1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MonitorArcL1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MonitorArcR1 = lv_arc_create(ui_Monitor);
    lv_obj_set_width(ui_MonitorArcR1, 222);
    lv_obj_set_height(ui_MonitorArcR1, 222);
    lv_obj_set_align(ui_MonitorArcR1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MonitorArcR1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_MonitorArcR1, 0, 6000);
    lv_arc_set_value(ui_MonitorArcR1, 1500);
    lv_obj_set_style_arc_width(ui_MonitorArcR1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MonitorArcR1, lv_color_hex(0x92FFC8), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MonitorArcR1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MonitorArcR1, 9, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_MonitorArcR1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MonitorArcR1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MonitorArcR1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MonitorArcL2 = lv_arc_create(ui_Monitor);
    lv_obj_set_width(ui_MonitorArcL2, 200);
    lv_obj_set_height(ui_MonitorArcL2, 200);
    lv_obj_set_align(ui_MonitorArcL2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MonitorArcL2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_MonitorArcL2, 0, 6000);
    lv_arc_set_value(ui_MonitorArcL2, 1400);
    lv_obj_set_style_arc_width(ui_MonitorArcL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MonitorArcL2, lv_color_hex(0x529070), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MonitorArcL2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MonitorArcL2, 9, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_MonitorArcL2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MonitorArcL2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MonitorArcL2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MonitorArcR2 = lv_arc_create(ui_Monitor);
    lv_obj_set_width(ui_MonitorArcR2, 182);
    lv_obj_set_height(ui_MonitorArcR2, 182);
    lv_obj_set_align(ui_MonitorArcR2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MonitorArcR2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_MonitorArcR2, 0, 6000);
    lv_arc_set_value(ui_MonitorArcR2, 1500);
    lv_obj_set_style_arc_width(ui_MonitorArcR2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MonitorArcR2, lv_color_hex(0x529070), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MonitorArcR2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MonitorArcR2, 9, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_MonitorArcR2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MonitorArcR2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MonitorArcR2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MonitorArcL3 = lv_arc_create(ui_Monitor);
    lv_obj_set_width(ui_MonitorArcL3, 160);
    lv_obj_set_height(ui_MonitorArcL3, 160);
    lv_obj_set_align(ui_MonitorArcL3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MonitorArcL3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_MonitorArcL3, 0, 6000);
    lv_arc_set_value(ui_MonitorArcL3, 1400);
    lv_obj_set_style_arc_width(ui_MonitorArcL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MonitorArcL3, lv_color_hex(0x529070), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MonitorArcL3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MonitorArcL3, 9, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_MonitorArcL3, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MonitorArcL3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MonitorArcL3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MonitorArcR3 = lv_arc_create(ui_Monitor);
    lv_obj_set_width(ui_MonitorArcR3, 142);
    lv_obj_set_height(ui_MonitorArcR3, 142);
    lv_obj_set_align(ui_MonitorArcR3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MonitorArcR3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_MonitorArcR3, 0, 6000);
    lv_arc_set_value(ui_MonitorArcR3, 1500);
    lv_obj_set_style_arc_width(ui_MonitorArcR3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MonitorArcR3, lv_color_hex(0x529070), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MonitorArcR3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MonitorArcR3, 9, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_MonitorArcR3, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MonitorArcR3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MonitorArcR3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelArcLevel = lv_label_create(ui_Monitor);
    lv_obj_set_width(ui_LabelArcLevel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArcLevel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelArcLevel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelArcLevel, "-33dB");
    lv_obj_add_flag(ui_LabelArcLevel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelArcLevel, lv_color_hex(0x73C29C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelArcLevel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelArcLevel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_LabelArcLevel, ui_event_LabelArcLevel, LV_EVENT_ALL, NULL);

}

void ui_Monitor_screen_destroy(void)
{
    if(ui_Monitor) lv_obj_del(ui_Monitor);

    // NULL screen variables
    ui_Monitor = NULL;
    ui_LevelArc1 = NULL;
    ui_LevelArc2 = NULL;
    ui_LevelArc3 = NULL;
    ui_MonitorArcL1 = NULL;
    ui_MonitorArcR1 = NULL;
    ui_MonitorArcL2 = NULL;
    ui_MonitorArcR2 = NULL;
    ui_MonitorArcL3 = NULL;
    ui_MonitorArcR3 = NULL;
    ui_LabelArcLevel = NULL;

}
