// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_MONITOR_H
#define UI_MONITOR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Monitor
extern void ui_Monitor_screen_init(void);
extern void ui_Monitor_screen_destroy(void);
extern void ui_event_Monitor(lv_event_t * e);
extern lv_obj_t * ui_Monitor;
extern lv_obj_t * ui_LevelArc1;
extern lv_obj_t * ui_LevelArc2;
extern lv_obj_t * ui_LevelArc3;
extern lv_obj_t * ui_MonitorArcL1;
extern lv_obj_t * ui_MonitorArcR1;
extern lv_obj_t * ui_MonitorArcL2;
extern lv_obj_t * ui_MonitorArcR2;
extern lv_obj_t * ui_MonitorArcL3;
extern lv_obj_t * ui_MonitorArcR3;
extern void ui_event_LabelArcLevel(lv_event_t * e);
extern lv_obj_t * ui_LabelArcLevel;
extern void ui_event_OutputButtonPreviewContainer(lv_event_t * e);
extern lv_obj_t * ui_OutputButtonPreviewContainer;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_MonitorDecrementSelectedChannel;
extern lv_obj_t * ui_MonitorIncrementSelectedChannel;
extern lv_obj_t * ui_BatteryBar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

