// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Monitor = NULL;
lv_obj_t * ui_LevelArc1 = NULL;
lv_obj_t * ui_LevelArc2 = NULL;
lv_obj_t * ui_LevelArc3 = NULL;
lv_obj_t * ui_MonitorArcL1 = NULL;
lv_obj_t * ui_MonitorArcR1 = NULL;
lv_obj_t * ui_MonitorArcL2 = NULL;
lv_obj_t * ui_MonitorArcR2 = NULL;
lv_obj_t * ui_MonitorArcL3 = NULL;
lv_obj_t * ui_MonitorArcR3 = NULL;
lv_obj_t * ui_LabelArcLevel = NULL;
lv_obj_t * ui_OutputButtonPreviewContainer = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Panel9 = NULL;
// event funtions
void ui_event_LabelArcLevel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_Config, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 300, 0, &ui_Config_screen_init);
    }
}

void ui_event_OutputButtonPreviewContainer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_OutputMatrix, LV_SCR_LOAD_ANIM_MOVE_TOP, 300, 0, &ui_OutputMatrix_screen_init);
    }
}

// build funtions

void ui_Monitor_screen_init(void)
{
    ui_Monitor = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Monitor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LevelArc1 = lv_arc_create(ui_Monitor);
    lv_obj_set_width(ui_LevelArc1, 240);
    lv_obj_set_height(ui_LevelArc1, 240);
    lv_obj_set_align(ui_LevelArc1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_LevelArc1, 0, 6000);
    lv_arc_set_value(ui_LevelArc1, 2500);
    lv_obj_set_style_arc_width(ui_LevelArc1, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_LevelArc1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_LevelArc1, lv_color_hex(0x70C399), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_LevelArc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_LevelArc1, 18, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_LevelArc1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LevelArc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LevelArc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LevelArc2 = lv_arc_create(ui_Monitor);
    lv_obj_set_width(ui_LevelArc2, 200);
    lv_obj_set_height(ui_LevelArc2, 200);
    lv_obj_set_align(ui_LevelArc2, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_LevelArc2, 0, 6000);
    lv_arc_set_value(ui_LevelArc2, 2500);
    lv_obj_set_style_arc_width(ui_LevelArc2, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_LevelArc2, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_LevelArc2, lv_color_hex(0x44765C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_LevelArc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_LevelArc2, 18, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_LevelArc2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LevelArc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LevelArc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LevelArc3 = lv_arc_create(ui_Monitor);
    lv_obj_set_width(ui_LevelArc3, 160);
    lv_obj_set_height(ui_LevelArc3, 160);
    lv_obj_set_align(ui_LevelArc3, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_LevelArc3, 0, 6000);
    lv_arc_set_value(ui_LevelArc3, 2500);
    lv_obj_set_style_arc_width(ui_LevelArc3, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_LevelArc3, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_LevelArc3, lv_color_hex(0x44765C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_LevelArc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_LevelArc3, 18, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_LevelArc3, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LevelArc3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LevelArc3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MonitorArcL1 = lv_arc_create(ui_Monitor);
    lv_obj_set_width(ui_MonitorArcL1, 240);
    lv_obj_set_height(ui_MonitorArcL1, 240);
    lv_obj_set_align(ui_MonitorArcL1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MonitorArcL1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_MonitorArcL1, 0, 6000);
    lv_arc_set_value(ui_MonitorArcL1, 1400);
    lv_obj_set_style_arc_width(ui_MonitorArcL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MonitorArcL1, lv_color_hex(0x92FFC8), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MonitorArcL1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MonitorArcL1, 9, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_MonitorArcL1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MonitorArcL1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MonitorArcL1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MonitorArcR1 = lv_arc_create(ui_Monitor);
    lv_obj_set_width(ui_MonitorArcR1, 222);
    lv_obj_set_height(ui_MonitorArcR1, 222);
    lv_obj_set_align(ui_MonitorArcR1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MonitorArcR1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_MonitorArcR1, 0, 6000);
    lv_arc_set_value(ui_MonitorArcR1, 1500);
    lv_obj_set_style_arc_width(ui_MonitorArcR1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MonitorArcR1, lv_color_hex(0x92FFC8), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MonitorArcR1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MonitorArcR1, 9, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_MonitorArcR1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MonitorArcR1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MonitorArcR1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MonitorArcL2 = lv_arc_create(ui_Monitor);
    lv_obj_set_width(ui_MonitorArcL2, 200);
    lv_obj_set_height(ui_MonitorArcL2, 200);
    lv_obj_set_align(ui_MonitorArcL2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MonitorArcL2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_MonitorArcL2, 0, 6000);
    lv_arc_set_value(ui_MonitorArcL2, 1400);
    lv_obj_set_style_arc_width(ui_MonitorArcL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MonitorArcL2, lv_color_hex(0x529070), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MonitorArcL2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MonitorArcL2, 9, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_MonitorArcL2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MonitorArcL2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MonitorArcL2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MonitorArcR2 = lv_arc_create(ui_Monitor);
    lv_obj_set_width(ui_MonitorArcR2, 182);
    lv_obj_set_height(ui_MonitorArcR2, 182);
    lv_obj_set_align(ui_MonitorArcR2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MonitorArcR2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_MonitorArcR2, 0, 6000);
    lv_arc_set_value(ui_MonitorArcR2, 1500);
    lv_obj_set_style_arc_width(ui_MonitorArcR2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MonitorArcR2, lv_color_hex(0x529070), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MonitorArcR2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MonitorArcR2, 9, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_MonitorArcR2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MonitorArcR2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MonitorArcR2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MonitorArcL3 = lv_arc_create(ui_Monitor);
    lv_obj_set_width(ui_MonitorArcL3, 160);
    lv_obj_set_height(ui_MonitorArcL3, 160);
    lv_obj_set_align(ui_MonitorArcL3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MonitorArcL3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_MonitorArcL3, 0, 6000);
    lv_arc_set_value(ui_MonitorArcL3, 1400);
    lv_obj_set_style_arc_width(ui_MonitorArcL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MonitorArcL3, lv_color_hex(0x529070), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MonitorArcL3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MonitorArcL3, 9, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_MonitorArcL3, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MonitorArcL3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MonitorArcL3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MonitorArcR3 = lv_arc_create(ui_Monitor);
    lv_obj_set_width(ui_MonitorArcR3, 142);
    lv_obj_set_height(ui_MonitorArcR3, 142);
    lv_obj_set_align(ui_MonitorArcR3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MonitorArcR3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_MonitorArcR3, 0, 6000);
    lv_arc_set_value(ui_MonitorArcR3, 1500);
    lv_obj_set_style_arc_width(ui_MonitorArcR3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MonitorArcR3, lv_color_hex(0x529070), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MonitorArcR3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MonitorArcR3, 9, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_MonitorArcR3, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MonitorArcR3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MonitorArcR3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelArcLevel = lv_label_create(ui_Monitor);
    lv_obj_set_width(ui_LabelArcLevel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArcLevel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelArcLevel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelArcLevel, "-33dB");
    lv_obj_add_flag(ui_LabelArcLevel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelArcLevel, lv_color_hex(0x73C29C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelArcLevel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelArcLevel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OutputButtonPreviewContainer = lv_obj_create(ui_Monitor);
    lv_obj_remove_style_all(ui_OutputButtonPreviewContainer);
    lv_obj_set_width(ui_OutputButtonPreviewContainer, 65);
    lv_obj_set_height(ui_OutputButtonPreviewContainer, 65);
    lv_obj_set_x(ui_OutputButtonPreviewContainer, 0);
    lv_obj_set_y(ui_OutputButtonPreviewContainer, 85);
    lv_obj_set_align(ui_OutputButtonPreviewContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_OutputButtonPreviewContainer, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_OutputButtonPreviewContainer, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_remove_flag(ui_OutputButtonPreviewContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_OutputButtonPreviewContainer);
    lv_obj_set_width(ui_Panel1, 17);
    lv_obj_set_height(ui_Panel1, 17);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x2C3D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x529070), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Panel2 = lv_obj_create(ui_OutputButtonPreviewContainer);
    lv_obj_set_width(ui_Panel2, 17);
    lv_obj_set_height(ui_Panel2, 17);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x2C3D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x529070), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Panel3 = lv_obj_create(ui_OutputButtonPreviewContainer);
    lv_obj_set_width(ui_Panel3, 17);
    lv_obj_set_height(ui_Panel3, 17);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x2C3D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x529070), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Panel4 = lv_obj_create(ui_OutputButtonPreviewContainer);
    lv_obj_set_width(ui_Panel4, 17);
    lv_obj_set_height(ui_Panel4, 17);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x2C3D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x529070), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Panel5 = lv_obj_create(ui_OutputButtonPreviewContainer);
    lv_obj_set_width(ui_Panel5, 17);
    lv_obj_set_height(ui_Panel5, 17);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x2C3D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x529070), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Panel6 = lv_obj_create(ui_OutputButtonPreviewContainer);
    lv_obj_set_width(ui_Panel6, 17);
    lv_obj_set_height(ui_Panel6, 17);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x2C3D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x529070), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Panel7 = lv_obj_create(ui_OutputButtonPreviewContainer);
    lv_obj_set_width(ui_Panel7, 17);
    lv_obj_set_height(ui_Panel7, 17);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x2C3D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x529070), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Panel8 = lv_obj_create(ui_OutputButtonPreviewContainer);
    lv_obj_set_width(ui_Panel8, 17);
    lv_obj_set_height(ui_Panel8, 17);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x2C3D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x529070), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Panel9 = lv_obj_create(ui_OutputButtonPreviewContainer);
    lv_obj_set_width(ui_Panel9, 17);
    lv_obj_set_height(ui_Panel9, 17);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x2C3D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel9, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x529070), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_LabelArcLevel, ui_event_LabelArcLevel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OutputButtonPreviewContainer, ui_event_OutputButtonPreviewContainer, LV_EVENT_ALL, NULL);

}

void ui_Monitor_screen_destroy(void)
{
    if(ui_Monitor) lv_obj_del(ui_Monitor);

    // NULL screen variables
    ui_Monitor = NULL;
    ui_LevelArc1 = NULL;
    ui_LevelArc2 = NULL;
    ui_LevelArc3 = NULL;
    ui_MonitorArcL1 = NULL;
    ui_MonitorArcR1 = NULL;
    ui_MonitorArcL2 = NULL;
    ui_MonitorArcR2 = NULL;
    ui_MonitorArcL3 = NULL;
    ui_MonitorArcR3 = NULL;
    ui_LabelArcLevel = NULL;
    ui_OutputButtonPreviewContainer = NULL;
    ui_Panel1 = NULL;
    ui_Panel2 = NULL;
    ui_Panel3 = NULL;
    ui_Panel4 = NULL;
    ui_Panel5 = NULL;
    ui_Panel6 = NULL;
    ui_Panel7 = NULL;
    ui_Panel8 = NULL;
    ui_Panel9 = NULL;

}
