// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_OutputMatrix = NULL;
lv_obj_t * ui_OutputButtonContainer = NULL;
lv_obj_t * ui_Strip1ButtonA1 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Strip1ButtonA2 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Strip1ButtonA3 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Strip1ButtonA6 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Strip1ButtonA8 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Strip1ButtonA9 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Strip1ButtonA10 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Strip1ButtonA11 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Strip1ButtonA12 = NULL;
lv_obj_t * ui_Label11 = NULL;
// event funtions
void ui_event_OutputMatrix(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Monitor, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 300, 0, &ui_Monitor_screen_init);
    }
}

// build funtions

void ui_OutputMatrix_screen_init(void)
{
    ui_OutputMatrix = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_OutputMatrix, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OutputMatrix, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_OutputMatrix, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_OutputButtonContainer = lv_obj_create(ui_OutputMatrix);
    lv_obj_remove_style_all(ui_OutputButtonContainer);
    lv_obj_set_width(ui_OutputButtonContainer, 200);
    lv_obj_set_height(ui_OutputButtonContainer, 200);
    lv_obj_set_align(ui_OutputButtonContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_OutputButtonContainer, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_OutputButtonContainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_remove_flag(ui_OutputButtonContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Strip1ButtonA1 = lv_button_create(ui_OutputButtonContainer);
    lv_obj_set_width(ui_Strip1ButtonA1, lv_pct(30));
    lv_obj_set_height(ui_Strip1ButtonA1, lv_pct(30));
    lv_obj_set_align(ui_Strip1ButtonA1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Strip1ButtonA1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Strip1ButtonA1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Strip1ButtonA1, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Strip1ButtonA1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Strip1ButtonA1, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Strip1ButtonA1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Strip1ButtonA1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Strip1ButtonA1, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Strip1ButtonA1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Strip1ButtonA1, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Strip1ButtonA1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Strip1ButtonA1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Strip1ButtonA1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label4 = lv_label_create(ui_Strip1ButtonA1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "A1");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Strip1ButtonA2 = lv_button_create(ui_OutputButtonContainer);
    lv_obj_set_width(ui_Strip1ButtonA2, lv_pct(30));
    lv_obj_set_height(ui_Strip1ButtonA2, lv_pct(30));
    lv_obj_set_align(ui_Strip1ButtonA2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Strip1ButtonA2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Strip1ButtonA2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Strip1ButtonA2, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Strip1ButtonA2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Strip1ButtonA2, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Strip1ButtonA2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Strip1ButtonA2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Strip1ButtonA2, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Strip1ButtonA2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Strip1ButtonA2, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Strip1ButtonA2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Strip1ButtonA2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Strip1ButtonA2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label1 = lv_label_create(ui_Strip1ButtonA2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "A2");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Strip1ButtonA3 = lv_button_create(ui_OutputButtonContainer);
    lv_obj_set_width(ui_Strip1ButtonA3, lv_pct(30));
    lv_obj_set_height(ui_Strip1ButtonA3, lv_pct(30));
    lv_obj_set_align(ui_Strip1ButtonA3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Strip1ButtonA3, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Strip1ButtonA3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Strip1ButtonA3, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Strip1ButtonA3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Strip1ButtonA3, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Strip1ButtonA3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Strip1ButtonA3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Strip1ButtonA3, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Strip1ButtonA3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Strip1ButtonA3, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Strip1ButtonA3, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Strip1ButtonA3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Strip1ButtonA3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label3 = lv_label_create(ui_Strip1ButtonA3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "A3");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Strip1ButtonA6 = lv_button_create(ui_OutputButtonContainer);
    lv_obj_set_width(ui_Strip1ButtonA6, lv_pct(30));
    lv_obj_set_height(ui_Strip1ButtonA6, lv_pct(30));
    lv_obj_set_align(ui_Strip1ButtonA6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Strip1ButtonA6, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Strip1ButtonA6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Strip1ButtonA6, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Strip1ButtonA6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Strip1ButtonA6, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Strip1ButtonA6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Strip1ButtonA6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Strip1ButtonA6, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Strip1ButtonA6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Strip1ButtonA6, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Strip1ButtonA6, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Strip1ButtonA6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Strip1ButtonA6, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label5 = lv_label_create(ui_Strip1ButtonA6);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "A1");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Strip1ButtonA8 = lv_button_create(ui_OutputButtonContainer);
    lv_obj_set_width(ui_Strip1ButtonA8, lv_pct(30));
    lv_obj_set_height(ui_Strip1ButtonA8, lv_pct(30));
    lv_obj_set_align(ui_Strip1ButtonA8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Strip1ButtonA8, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Strip1ButtonA8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Strip1ButtonA8, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Strip1ButtonA8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Strip1ButtonA8, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Strip1ButtonA8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Strip1ButtonA8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Strip1ButtonA8, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Strip1ButtonA8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Strip1ButtonA8, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Strip1ButtonA8, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Strip1ButtonA8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Strip1ButtonA8, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label7 = lv_label_create(ui_Strip1ButtonA8);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "A2");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Strip1ButtonA9 = lv_button_create(ui_OutputButtonContainer);
    lv_obj_set_width(ui_Strip1ButtonA9, lv_pct(30));
    lv_obj_set_height(ui_Strip1ButtonA9, lv_pct(30));
    lv_obj_set_align(ui_Strip1ButtonA9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Strip1ButtonA9, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Strip1ButtonA9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Strip1ButtonA9, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Strip1ButtonA9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Strip1ButtonA9, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Strip1ButtonA9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Strip1ButtonA9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Strip1ButtonA9, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Strip1ButtonA9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Strip1ButtonA9, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Strip1ButtonA9, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Strip1ButtonA9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Strip1ButtonA9, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label8 = lv_label_create(ui_Strip1ButtonA9);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "A3");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Strip1ButtonA10 = lv_button_create(ui_OutputButtonContainer);
    lv_obj_set_width(ui_Strip1ButtonA10, lv_pct(30));
    lv_obj_set_height(ui_Strip1ButtonA10, lv_pct(30));
    lv_obj_set_align(ui_Strip1ButtonA10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Strip1ButtonA10, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Strip1ButtonA10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Strip1ButtonA10, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Strip1ButtonA10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Strip1ButtonA10, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Strip1ButtonA10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Strip1ButtonA10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Strip1ButtonA10, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Strip1ButtonA10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Strip1ButtonA10, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Strip1ButtonA10, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Strip1ButtonA10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Strip1ButtonA10, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label9 = lv_label_create(ui_Strip1ButtonA10);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "A1");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Strip1ButtonA11 = lv_button_create(ui_OutputButtonContainer);
    lv_obj_set_width(ui_Strip1ButtonA11, lv_pct(30));
    lv_obj_set_height(ui_Strip1ButtonA11, lv_pct(30));
    lv_obj_set_align(ui_Strip1ButtonA11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Strip1ButtonA11, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Strip1ButtonA11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Strip1ButtonA11, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Strip1ButtonA11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Strip1ButtonA11, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Strip1ButtonA11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Strip1ButtonA11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Strip1ButtonA11, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Strip1ButtonA11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Strip1ButtonA11, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Strip1ButtonA11, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Strip1ButtonA11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Strip1ButtonA11, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label10 = lv_label_create(ui_Strip1ButtonA11);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "A2");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Strip1ButtonA12 = lv_button_create(ui_OutputButtonContainer);
    lv_obj_set_width(ui_Strip1ButtonA12, lv_pct(30));
    lv_obj_set_height(ui_Strip1ButtonA12, lv_pct(30));
    lv_obj_set_align(ui_Strip1ButtonA12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Strip1ButtonA12, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Strip1ButtonA12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Strip1ButtonA12, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Strip1ButtonA12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Strip1ButtonA12, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Strip1ButtonA12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Strip1ButtonA12, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Strip1ButtonA12, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Strip1ButtonA12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Strip1ButtonA12, lv_color_hex(0x70C399), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Strip1ButtonA12, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Strip1ButtonA12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Strip1ButtonA12, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label11 = lv_label_create(ui_Strip1ButtonA12);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "A3");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_OutputMatrix, ui_event_OutputMatrix, LV_EVENT_ALL, NULL);

}

void ui_OutputMatrix_screen_destroy(void)
{
    if(ui_OutputMatrix) lv_obj_del(ui_OutputMatrix);

    // NULL screen variables
    ui_OutputMatrix = NULL;
    ui_OutputButtonContainer = NULL;
    ui_Strip1ButtonA1 = NULL;
    ui_Label4 = NULL;
    ui_Strip1ButtonA2 = NULL;
    ui_Label1 = NULL;
    ui_Strip1ButtonA3 = NULL;
    ui_Label3 = NULL;
    ui_Strip1ButtonA6 = NULL;
    ui_Label5 = NULL;
    ui_Strip1ButtonA8 = NULL;
    ui_Label7 = NULL;
    ui_Strip1ButtonA9 = NULL;
    ui_Label8 = NULL;
    ui_Strip1ButtonA10 = NULL;
    ui_Label9 = NULL;
    ui_Strip1ButtonA11 = NULL;
    ui_Label10 = NULL;
    ui_Strip1ButtonA12 = NULL;
    ui_Label11 = NULL;

}
