// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_OUTPUTMATRIX_H
#define UI_OUTPUTMATRIX_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_OutputMatrix
extern void ui_OutputMatrix_screen_init(void);
extern void ui_OutputMatrix_screen_destroy(void);
extern lv_obj_t * ui_OutputMatrix;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

