// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_OutputMatrix = NULL;
// event funtions

// build funtions

void ui_OutputMatrix_screen_init(void)
{
    ui_OutputMatrix = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_OutputMatrix, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_OutputMatrix_screen_destroy(void)
{
    if(ui_OutputMatrix) lv_obj_del(ui_OutputMatrix);

    // NULL screen variables
    ui_OutputMatrix = NULL;

}
